### ISSUE TITLE
Help wanted, how to move to the next cell?

### ISSUE THREAD

**Issue by BenSYZ** [ianhi/jupyterlab-vimrc#5]
Thanks for your extension! Like mentioned in the title, I find I cannot jump to the next cell with `j`(also not for `n` as I mapped), I wonder how to set it. 
By the way I want to map `'` to `:`, how to achieve it?

Here is my `vimrc` file
```json5
{
    // vimrc
    // jupyterlab-vimrc:vimrc
    // Settings to be applied to codemirror vim mode
    // *********************************************

    // imap commands
    // [lhs, rhs] - e.g. "imap": [["ii", "<Esc>"]]
    "imap": [],

    // inoremap commands
    // [lhs, rhs]
    "inoremap": [
        []
    ],

    // nmap commands
    // [lhs, rhs]
    "nmap": [],

    // nnoremap commands
    // [lhs, rhs]
    "nnoremap": [
        ['n','j'],
        ['e','k'],
        ['i','l'],
        ['m','n'],
        ['k','m'],
        ['f','e'],
        ['t','f'],
        ['l','u'],
        ['u','i'],
        
        ['N','J'],
        ['E','K'],
        ['I','L'],
        ['M','N'],
        ['K','M'],
        ['F','E'],
        ['T','F'],
        ['L','U'],
        ['U','I'],
        
    ],

    // vmap commands
    // [lhs, rhs]
    "vmap": [],

    // vnoremap commands
    // [lhs, rhs]
    "vnoremap": []
}
```

**Comment by ianhi** [comment]
Hi @BenSYZ 

> Thanks for your extension!

Thanks for using it!

> I find I cannot jump to the next cell with j(also not for n as I mapped), I wonder how to set it.

Oh huh that is pretty weird. I would have though that what you are doing would work. What's extra wild is that even just adding the `n`->`j` mapping also breaks switching cells with `k`. Also if I set this manually from inside the cell with `:nmap n j` the same breakage does not occur. 

I think this is some sort of bad interaction between this extension and the jupyterlab-vim extension that special cases `j` and `k` in order to have moving up and down see: https://github.com/axelfahy/jupyterlab-vim/blob/c4e43f940ef4be4c961608b6192412d2f3a33d1f/src/index.ts#L164-L173 I will try to find time to think about this week though I may not be able to get to this until this weekend. One workaround in the meantime may be to fork `jupyterlab-vim`, change the lines I linked to use `n` and `m` instead of j and k, and then install that dev version. I know that is not ideal but I'm a little mystified at the moment about how to best resolve this.



Also, I assume you are using 

> By the way I want to map ' to :, how to achieve it?

I imagine you only want to remap this in visual mode and normal mode? If so you should use the `nmap` and `vmap` commands (noremap didn't for me for this) with this remapping: `['\'', ':']`

```
    'nmap' : [
        ['\'', ':']
    ],
    'vmap' : [
        ['\'', ':']
    ]
```

**Comment by ianhi** [comment]
ok wow turns out i have a better workaround. I think this is something pathological due to have the `jupyterlab-vim` extension does a whole bunch of defining vim operations everytime you change cells in vim. I find that you can get it work with the following:
1. use `nmap` instead of `nnoremap` (not sure why but this is key)
2. after you change the settings use the mouse to change the active cell at least once
3. you will be able to switch cells

In this gif I am using `n` to move down cells:

![Peek 2020-08-02 23-57](https://user-images.githubusercontent.com/10111092/89144523-0b15cc80-d51c-11ea-9ca5-ca70601da79f.gif)

I'm not sure exactly what is causing this weird behavior, but wiht jlab3 there will more support for notebook vim in core and I think that this issue may be resolved naturally by that.

**Comment by BenSYZ** [comment]
Thanks for your constructive and clear suggestions. Both two way works well. Using `nmap` rather `nnormap` is a bit like that in VIM, you need `nnmap` for the key shortcut of calling a function.
